### ISSUE TITLE
[BUG] surrounding the wrong region.

### ISSUE THREAD

**Issue by amosbird** [timcharper/evil-surround#101] opened 2017-02-02 14:21 UTC
Here is the buffer that can be used to reproduce,
```
package cmd

import (
	"github.com/elazarl/goproxy"
	"github.com/spf13/cobra"
	"log"
	"net/http"
)

// httpCmd represents the http command
var httpCmd = &cobra.Command{
	Use:   "http",
	Short: "Start an http proxy.",
	Long:  `Start an http proxy.`,
	Run: func(cmd *cobra.Command, args []string) {
		proxy := goproxy.NewProxyHttpServer()
		proxy.Verbose = verbose
		log.Fatal(http.ListenAndServe(addr, proxy))
	},
}

func init() {
	RootCmd.AddCommand(httpCmd)
	httpCmd.Flags().StringVarP(&addr, "addr", "a", "127.0.0.1:8888", "proxy listening addr, <ip:port>")
	httpCmd.Flags().BoolVarP(&verbose, "verbose", "v", false, "verbose output.")
}
```

I did a terminal record to explain what happened, [asciinema](https://asciinema.org/a/e64cipvvhr263jevknjmsusxd)

**Comment by ninrod** [comment] 2017-02-02 15:54
Hi. I do not understand. What exact surround command are you trying to use here?

**Comment by ninrod** [comment] 2017-02-02 15:57
And please post what emacs version are you using, if it is spacemacs, and if your evil-surround version and evil-version are up-to-date.

**Comment by amosbird** [comment] 2017-02-03 01:14
The command is  `evil-change` + `evil-inner-double-quoto`. I use `emacs 25.1.1`, `spacemacs 0.200.7`, `Evil version evil-git-4e7d80b` and `evil-surround 20170124.1110`.

**Comment by ninrod** [comment] 2017-02-03 01:19
you mean `ci"`?

I just opened a buffer with your repro text and was not able to reproduce.

**Comment by ninrod** [comment] 2017-02-03 01:20
Also, that has nothing to do with evil-surround, I'm afraid. 

I think that you are dealing with plain evil-mode here.

**Comment by ninrod** [comment] 2017-02-03 01:24
you'd be using evil-surround if you had issued something like `csi")`.

**Comment by amosbird** [comment] 2017-02-03 01:50
oh, I see. Hmm, what is your env? Do you use `spacemacs`?

**Comment by ninrod** [comment] 2017-02-03 10:52
my entire env is here: [ninrod/dotfiles](http://github.com/ninrod/dotfiles).

I don't use spacemacs. My own emacs config is [here](https://github.com/ninrod/dotfiles/blob/master/emacs/boot.org).

**Comment by ninrod** [comment] 2017-02-03 10:53
We should be closing this issue then. You seem to be having problems with the spacemacs configuration. If you are using an updated version of the config and still have problems, I recommend opening an issue against spacemacs, filling out the spacemacs bug template.

**Closed by ninrod** 2017-02-03 10:53 UTC
