### ISSUE TITLE
. (dot) does not always work

### ISSUE THREAD

**Issue by stefanalt** [timcharper/evil-surround#58] opened 2015-07-22 22:34 UTC
Repeating surround changes with dot e.g. works for:

    cs"(
    ds(

It however does not work for many other cases (e.g.):

    ysiw<pre>
    cst<stong>

I checked that vim-surround also has some limitations, but
hopefully you dont try to be 100% compatible ;-)

All executed from normal mode

**Comment by sooheon** [comment] 2015-09-04 00:59
Most importantly,  the `ys` and `cs` operations work under vim but do not work with evil, so this is a regression from upstream. Is it clear why the dot operation doesn't work?

**Comment by timcharper** [comment] 2015-12-10 20:13
Duplicate of #24

**Closed by timcharper** 2015-12-10 20:13 UTC
